print ('1.Nume Prenume: Andrei Axenti')
print ('2.Data, anul nasterii: 06.11.2004 ')
print ('3.Domiciuliu: str. Puschin 29/9')
print ('4.Numarul de Telefon: 060737995')
print ('5.Adresa de e-mail: andreiaxenti799@gmail.com')
print ('6.Statut civil: Celibatar')
print ('7.Nationalitate: Moldovean')
print ('8.Limbi vorbite: Romana, franceza, engleza, rusa')
print ('9.Religie: Crestinism ortodox')
print ('10.Codul Postal: MD-3110')
print ('11.Functie: Elev')